/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jila_number_Dylib */

#ifndef _Included_com_jila_number_Dylib
#define _Included_com_jila_number_Dylib
#ifdef __cplusplus
extern "C" {
#endif

#include <android/asset_manager.h>
AAssetManager* g_am;

/*
 * Class:     com_jila_number_Dylib
 * Method:    initializeDylib
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jila_number_Dylib_initializeDylib
  (JNIEnv *, jobject, jstring,jobject param4am);

/*
 * Class:     com_jila_number_Dylib
 * Method:    finalizeDylib
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jila_number_Dylib_finalizeDylib
  (JNIEnv *, jobject, jstring);



#ifdef __cplusplus
}
#endif
#endif
